# Generated by Django 5.2.11 on 2026-02-05 14:28

import alumniportal.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('course', models.CharField(max_length=100)),
                ('batch', models.CharField(max_length=50)),
                ('current_designation', models.CharField(max_length=200)),
                ('is_registered', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CommitteeYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_range', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='DistinguishedCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='EventFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='HomeSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='home_slider/', validators=[alumniportal.models.validate_image])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OfficeBearer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('designation', models.CharField(max_length=200)),
                ('qualification', models.CharField(blank=True, max_length=200)),
                ('message', models.TextField()),
                ('image', models.ImageField(upload_to='office_bearers/', validators=[alumniportal.models.validate_image])),
            ],
        ),
        migrations.CreateModel(
            name='RegisterLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='SuggestionLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('course', models.CharField(max_length=100)),
                ('batch', models.CharField(max_length=50)),
                ('linkedin_url', models.URLField(blank=True)),
                ('message', models.TextField()),
                ('image', models.ImageField(upload_to='testimonials/', validators=[alumniportal.models.validate_image])),
            ],
        ),
        migrations.CreateModel(
            name='CommitteeMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('department', models.CharField(max_length=200)),
                ('designation', models.CharField(max_length=200)),
                ('committee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumniportal.committeeyear')),
            ],
        ),
        migrations.CreateModel(
            name='DistinguishedAlumni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('course', models.CharField(max_length=100)),
                ('batch', models.CharField(max_length=50)),
                ('current_position', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='distinguished/', validators=[alumniportal.models.validate_image])),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumniportal.distinguishedcategory')),
            ],
        ),
        migrations.CreateModel(
            name='EventImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='events/', validators=[alumniportal.models.validate_image])),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumniportal.eventfolder')),
            ],
        ),
    ]
