# Generated by Django 5.2.11 on 2026-02-05 19:28

import alumniportal.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumniportal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollegeOfficeBearer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('designation', models.CharField(max_length=200)),
                ('qualification', models.CharField(blank=True, max_length=200)),
                ('image', models.ImageField(upload_to='college_office_bearers/', validators=[alumniportal.models.validate_image])),
            ],
        ),
    ]
