# Generated by Django 5.2.11 on 2026-02-06 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumniportal', '0002_collegeofficebearer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collegeofficebearer',
            name='qualification',
        ),
        migrations.RemoveField(
            model_name='committeemember',
            name='designation',
        ),
    ]
