# Generated by Django 5.2.11 on 2026-02-06 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumniportal', '0003_remove_collegeofficebearer_qualification_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimonial',
            name='linkedin_url',
        ),
        migrations.AddField(
            model_name='testimonial',
            name='linkedin',
            field=models.URLField(blank=True, null=True),
        ),
    ]
