# Generated by Django 5.2.11 on 2026-02-06 14:34

import alumniportal.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumniportal', '0005_testimonial_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssociationBearer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('designation', models.CharField(max_length=200)),
                ('qualification', models.CharField(blank=True, max_length=200, null=True)),
                ('message', models.TextField()),
                ('image', models.ImageField(upload_to='office_bearers/', validators=[alumniportal.models.validate_image])),
            ],
        ),
        migrations.DeleteModel(
            name='OfficeBearer',
        ),
    ]
