# Generated by Django 5.2.11 on 2026-02-06 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumniportal', '0006_associationbearer_delete_officebearer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='associationbearer',
            options={'ordering': ['position']},
        ),
        migrations.AddField(
            model_name='associationbearer',
            name='position',
            field=models.PositiveIntegerField(default=0, help_text='Kam number wala sabse uper dikhega (Eg: 1, 2, 3)'),
        ),
    ]
