# Generated by Django 5.2.11 on 2026-02-06 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumniportal', '0007_alter_associationbearer_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collegeofficebearer',
            options={'ordering': ['position']},
        ),
        migrations.AlterModelOptions(
            name='committeemember',
            options={'ordering': ['position']},
        ),
        migrations.AlterModelOptions(
            name='committeeyear',
            options={'ordering': ['position']},
        ),
        migrations.AlterModelOptions(
            name='distinguishedalumni',
            options={'ordering': ['position']},
        ),
        migrations.AlterModelOptions(
            name='distinguishedcategory',
            options={'ordering': ['position']},
        ),
        migrations.AlterModelOptions(
            name='eventfolder',
            options={'ordering': ['position']},
        ),
        migrations.AlterModelOptions(
            name='eventimage',
            options={'ordering': ['position']},
        ),
        migrations.AlterModelOptions(
            name='homeslider',
            options={'ordering': ['position']},
        ),
        migrations.AlterModelOptions(
            name='testimonial',
            options={'ordering': ['position']},
        ),
        migrations.AddField(
            model_name='collegeofficebearer',
            name='position',
            field=models.PositiveIntegerField(default=0, help_text='(Eg: 1, 2, 3)'),
        ),
        migrations.AddField(
            model_name='committeemember',
            name='position',
            field=models.PositiveIntegerField(default=0, help_text='(Eg: 1, 2, 3)'),
        ),
        migrations.AddField(
            model_name='committeeyear',
            name='position',
            field=models.PositiveIntegerField(default=0, help_text='(Eg: 1, 2, 3)'),
        ),
        migrations.AddField(
            model_name='distinguishedalumni',
            name='position',
            field=models.PositiveIntegerField(default=0, help_text='(Eg: 1, 2, 3)'),
        ),
        migrations.AddField(
            model_name='distinguishedcategory',
            name='position',
            field=models.PositiveIntegerField(default=0, help_text='(Eg: 1, 2, 3)'),
        ),
        migrations.AddField(
            model_name='eventfolder',
            name='position',
            field=models.PositiveIntegerField(default=0, help_text='(Eg: 1, 2, 3)'),
        ),
        migrations.AddField(
            model_name='eventimage',
            name='position',
            field=models.PositiveIntegerField(default=0, help_text='(Eg: 1, 2, 3)'),
        ),
        migrations.AddField(
            model_name='homeslider',
            name='position',
            field=models.PositiveIntegerField(default=0, help_text='(Eg: 1, 2, 3)'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='position',
            field=models.PositiveIntegerField(default=0, help_text='(Eg: 1, 2, 3)'),
        ),
        migrations.AlterField(
            model_name='associationbearer',
            name='position',
            field=models.PositiveIntegerField(default=0, help_text='(Eg: 1, 2, 3)'),
        ),
    ]
