# Generated by Django 5.2.11 on 2026-02-06 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumniportal', '0008_alter_collegeofficebearer_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alumni',
            options={'ordering': ['position']},
        ),
        migrations.AddField(
            model_name='alumni',
            name='position',
            field=models.PositiveIntegerField(default=0, help_text='(Eg: 1, 2, 3)'),
        ),
    ]
