# Generated by Django 5.2.11 on 2026-02-06 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumniportal', '0009_alter_alumni_options_alumni_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumni',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='alumni',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
