# Generated by Django 5.2.11 on 2026-02-08 18:23

import alumniportal.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumniportal', '0014_alter_associationbearer_image_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='alumni',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alumni',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='distinguishedalumni',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='distinguishedalumni',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='associationbearer',
            name='image',
            field=models.ImageField(upload_to='office_bearers/', validators=[alumniportal.models.validate_image]),
        ),
        migrations.AlterField(
            model_name='collegeofficebearer',
            name='image',
            field=models.ImageField(upload_to='college_office_bearers/', validators=[alumniportal.models.validate_image]),
        ),
        migrations.AlterField(
            model_name='distinguishedalumni',
            name='image',
            field=models.ImageField(upload_to='distinguished/', validators=[alumniportal.models.validate_image]),
        ),
        migrations.AlterField(
            model_name='homeslider',
            name='image',
            field=models.ImageField(upload_to='home_slider/', validators=[alumniportal.models.validate_image]),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='image',
            field=models.ImageField(upload_to='testimonials/', validators=[alumniportal.models.validate_image]),
        ),
        migrations.CreateModel(
            name='AdminProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('superadmin', 'Super Admin'), ('admin', 'Admin')], default='admin', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
