# Generated by Django 5.2.11 on 2026-02-11 21:02

import alumniportal.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumniportal', '0015_alumni_deleted_at_alumni_is_deleted_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_name', models.BooleanField(default=True)),
                ('show_batch', models.BooleanField(default=True)),
                ('show_course', models.BooleanField(default=True)),
                ('show_designation', models.BooleanField(default=True)),
                ('show_company', models.BooleanField(default=False)),
                ('show_email', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterModelOptions(
            name='alumni',
            options={},
        ),
        migrations.AlterField(
            model_name='alumni',
            name='batch',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='alumni',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='associationbearer',
            name='image',
            field=models.ImageField(upload_to='office_bearers/', validators=[alumniportal.models.validate_image]),
        ),
        migrations.AlterField(
            model_name='collegeofficebearer',
            name='image',
            field=models.ImageField(upload_to='college_office_bearers/', validators=[alumniportal.models.validate_image]),
        ),
        migrations.AlterField(
            model_name='distinguishedalumni',
            name='image',
            field=models.ImageField(upload_to='distinguished/', validators=[alumniportal.models.validate_image]),
        ),
        migrations.AlterField(
            model_name='homeslider',
            name='image',
            field=models.ImageField(upload_to='home_slider/', validators=[alumniportal.models.validate_image]),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='image',
            field=models.ImageField(upload_to='testimonials/', validators=[alumniportal.models.validate_image]),
        ),
    ]
