# Generated by Django 5.2.11 on 2026-02-14 20:50

import alumniportal.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumniportal', '0019_distinguishedcategory_deleted_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_title', models.CharField(default='Alumni Portal', max_length=200)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('allow_registration', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='associationbearer',
            name='image',
            field=models.ImageField(upload_to='office_bearers/', validators=[alumniportal.models.validate_image]),
        ),
        migrations.AlterField(
            model_name='collegeofficebearer',
            name='image',
            field=models.ImageField(upload_to='college_office_bearers/', validators=[alumniportal.models.validate_image]),
        ),
        migrations.AlterField(
            model_name='distinguishedalumni',
            name='image',
            field=models.ImageField(upload_to='distinguished/', validators=[alumniportal.models.validate_image]),
        ),
        migrations.AlterField(
            model_name='homeslider',
            name='image',
            field=models.ImageField(upload_to='home_slider/', validators=[alumniportal.models.validate_image]),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='image',
            field=models.ImageField(upload_to='testimonials/', validators=[alumniportal.models.validate_image]),
        ),
    ]
