# Generated by Django 5.2.11 on 2026-02-20 19:50

import alumniportal.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumniportal', '0022_academicdepartment_admindepartment_eventcategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumnievent',
            name='batch',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='alumnievent',
            name='resourse_person',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='associationbearer',
            name='image',
            field=models.ImageField(upload_to='office_bearers/', validators=[alumniportal.models.validate_image]),
        ),
        migrations.AlterField(
            model_name='collegeofficebearer',
            name='image',
            field=models.ImageField(upload_to='college_office_bearers/', validators=[alumniportal.models.validate_image]),
        ),
        migrations.AlterField(
            model_name='distinguishedalumni',
            name='image',
            field=models.ImageField(upload_to='distinguished/', validators=[alumniportal.models.validate_image]),
        ),
        migrations.AlterField(
            model_name='homeslider',
            name='image',
            field=models.ImageField(upload_to='home_slider/', validators=[alumniportal.models.validate_image]),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='image',
            field=models.ImageField(upload_to='testimonials/', validators=[alumniportal.models.validate_image]),
        ),
    ]
