# Generated by Django 5.2.11 on 2026-02-22 08:15

import alumniportal.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumniportal', '0027_alter_associationbearer_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collegeofficebearer',
            name='image',
            field=models.ImageField(upload_to='college_office_bearers/', validators=[alumniportal.models.validate_image]),
        ),
        migrations.AlterField(
            model_name='distinguishedalumni',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='distinguished/'),
        ),
        migrations.AlterField(
            model_name='homeslider',
            name='image',
            field=models.ImageField(upload_to='home_slider/', validators=[alumniportal.models.validate_image]),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='image',
            field=models.ImageField(upload_to='testimonials/', validators=[alumniportal.models.validate_image]),
        ),
    ]
